name: Leak Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Go Test
      env:
        CC: clang
        CXX: clang++
      run: |
        go test -c --tags leakcheck
        ./v8go.test
